#!/bin/bash
if (( $# < 1 ))
then
  cat ~/.xmltv/tv_grab_file.xmltv
  exit 0
fi

for arg in "$@"; do
    shift
    case "$arg" in
        "--description")  set -- "$@" "-d" ;;
        "--version")      set -- "$@" "-v" ;;
        "--capabilities") set -- "$@" "-c" ;;
        "--help")         set -- "$@" "-?" ;;
        *)                set -- "$@" "$arg"
    esac
done

while getopts "dvc" opt
do
    case "$opt" in
        "d") printf "tv_grab_file is a simple grabber that just read the ~/.xmltv/tv_grab_file.xmltv file or a given local or remote source\n"; exit 0 ;;
        "v") printf "0.1\n"; exit 0 ;;
        "c") printf "baseline\n"; exit 0 ;;
        "?") printf "Usage: %s: [--description] [--version] [--capabilities] [file|url]\n" $(basename $0); exit 2 ;;
    esac
done
shift $(expr $OPTIND - 1)

src=$1
if [[ "${src:0:4}" == "http" ]] || [[ "${src:0:3}" == "ftp" ]]; then
    curl -sL "$src"
else
    cat "$src"
fi
